// generated by scripts/gen-enums.ts — do not edit
//
// Sourced from the closed string unions in lib/types.ts. Re-run
// `npm run gen:enums` after changing a union covered here; CI fails the
// build if this file drifts from what that run would produce.

import { pgEnum } from "drizzle-orm/pg-core";

export const patientStatus = pgEnum("patient_status", ["active", "inactive", "new", "archived"]);
export const appointmentStatus = pgEnum("appointment_status", ["requested", "pending", "confirmed", "checked_in", "in_consultation", "completed", "cancelled", "rescheduled", "no_show"]);
export const doctorStatus = pgEnum("doctor_status", ["available", "in_consultation", "off_duty", "on_leave"]);
export const leadStage = pgEnum("lead_stage", ["new", "contacted", "qualified", "booked", "visited", "converted"]);
export const referralStatus = pgEnum("referral_status", ["received", "assigned", "contacted", "scheduled", "visited", "completed", "declined"]);
export const followUpStatus = pgEnum("follow_up_status", ["pending", "completed", "overdue", "scheduled"]);
export const taskStatus = pgEnum("task_status", ["todo", "in_progress", "blocked", "done"]);
export const caseStatus = pgEnum("case_status", ["new", "assigned", "investigating", "waiting", "resolved", "closed"]);
export const priority = pgEnum("priority", ["low", "medium", "high", "urgent"]);
export const channel = pgEnum("channel", ["sms", "email", "whatsapp", "call"]);
export const auditAction = pgEnum("audit_action", ["viewed", "revealed", "created", "updated", "deleted", "exported", "signed_in", "signed_out", "locked", "impersonation_started", "impersonation_ended"]);
export const notificationCategory = pgEnum("notification_category", ["appointments", "tasks", "leads", "follow_ups", "complaints", "system", "security"]);
export const tone = pgEnum("tone", ["success", "warning", "danger", "info", "ai", "neutral"]);
export const workflowNodeKind = pgEnum("workflow_node_kind", ["trigger", "action", "condition", "delay"]);
export const campaignStatus = pgEnum("campaign_status", ["draft", "scheduled", "running", "completed", "paused"]);
export const integrationStatus = pgEnum("integration_status", ["connected", "disconnected", "error", "pending"]);
export const staffStatus = pgEnum("staff_status", ["active", "invited", "suspended"]);
export const feedbackStatus = pgEnum("feedback_status", ["new", "reviewed", "actioned"]);
export const workflowStatus = pgEnum("workflow_status", ["live", "paused", "draft", "error"]);
export const messageDirection = pgEnum("message_direction", ["inbound", "outbound"]);
export const deliveryStatus = pgEnum("delivery_status", ["queued", "sent", "delivered", "opened", "clicked", "bounced", "failed"]);
export const deliveryEvent = pgEnum("delivery_event", ["queued", "sent", "delivered", "opened", "clicked", "bounced", "failed"]);
